# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kinsley/OneDrive/study/final_project/feedforward_closedloop_learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kinsley/OneDrive/study/final_project/feedforward_closedloop_learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kinsley/OneDrive/study/final_project/feedforward_closedloop_learning/CMakeFiles /home/kinsley/OneDrive/study/final_project/feedforward_closedloop_learning//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kinsley/OneDrive/study/final_project/feedforward_closedloop_learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fcl

# Build rule for target.
fcl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fcl
.PHONY : fcl

# fast build rule for target.
fcl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/build
.PHONY : fcl/fast

#=============================================================================
# Target rules for targets named fcl_static

# Build rule for target.
fcl_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fcl_static
.PHONY : fcl_static

# fast build rule for target.
fcl_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/build
.PHONY : fcl_static/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named test_bandpass

# Build rule for target.
test_bandpass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bandpass
.PHONY : test_bandpass

# fast build rule for target.
test_bandpass/fast:
	$(MAKE) $(MAKESILENT) -f tests_c/CMakeFiles/test_bandpass.dir/build.make tests_c/CMakeFiles/test_bandpass.dir/build
.PHONY : test_bandpass/fast

#=============================================================================
# Target rules for targets named test_fcl

# Build rule for target.
test_fcl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fcl
.PHONY : test_fcl

# fast build rule for target.
test_fcl/fast:
	$(MAKE) $(MAKESILENT) -f tests_c/CMakeFiles/test_fcl.dir/build.make tests_c/CMakeFiles/test_fcl.dir/build
.PHONY : test_fcl/fast

#=============================================================================
# Target rules for targets named test_layer

# Build rule for target.
test_layer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_layer
.PHONY : test_layer

# fast build rule for target.
test_layer/fast:
	$(MAKE) $(MAKESILENT) -f tests_c/CMakeFiles/test_layer.dir/build.make tests_c/CMakeFiles/test_layer.dir/build
.PHONY : test_layer/fast

#=============================================================================
# Target rules for targets named test_neuron

# Build rule for target.
test_neuron: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_neuron
.PHONY : test_neuron

# fast build rule for target.
test_neuron/fast:
	$(MAKE) $(MAKESILENT) -f tests_c/CMakeFiles/test_neuron.dir/build.make tests_c/CMakeFiles/test_neuron.dir/build
.PHONY : test_neuron/fast

#=============================================================================
# Target rules for targets named test_fcl_filters

# Build rule for target.
test_fcl_filters: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fcl_filters
.PHONY : test_fcl_filters

# fast build rule for target.
test_fcl_filters/fast:
	$(MAKE) $(MAKESILENT) -f tests_c/CMakeFiles/test_fcl_filters.dir/build.make tests_c/CMakeFiles/test_fcl_filters.dir/build
.PHONY : test_fcl_filters/fast

#=============================================================================
# Target rules for targets named linefollower

# Build rule for target.
linefollower: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linefollower
.PHONY : linefollower

# fast build rule for target.
linefollower/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/CMakeFiles/linefollower.dir/build.make linefollower/CMakeFiles/linefollower.dir/build
.PHONY : linefollower/fast

#=============================================================================
# Target rules for targets named linefollower_autogen_timestamp_deps

# Build rule for target.
linefollower_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linefollower_autogen_timestamp_deps
.PHONY : linefollower_autogen_timestamp_deps

# fast build rule for target.
linefollower_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/CMakeFiles/linefollower_autogen_timestamp_deps.dir/build.make linefollower/CMakeFiles/linefollower_autogen_timestamp_deps.dir/build
.PHONY : linefollower_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named linefollower_autogen

# Build rule for target.
linefollower_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linefollower_autogen
.PHONY : linefollower_autogen

# fast build rule for target.
linefollower_autogen/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/CMakeFiles/linefollower_autogen.dir/build.make linefollower/CMakeFiles/linefollower_autogen.dir/build
.PHONY : linefollower_autogen/fast

#=============================================================================
# Target rules for targets named cldl_static

# Build rule for target.
cldl_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cldl_static
.PHONY : cldl_static

# fast build rule for target.
cldl_static/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/cldl/CMakeFiles/cldl_static.dir/build.make linefollower/cldl/CMakeFiles/cldl_static.dir/build
.PHONY : cldl_static/fast

#=============================================================================
# Target rules for targets named linefollowercldl

# Build rule for target.
linefollowercldl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linefollowercldl
.PHONY : linefollowercldl

# fast build rule for target.
linefollowercldl/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/cldl/CMakeFiles/linefollowercldl.dir/build.make linefollower/cldl/CMakeFiles/linefollowercldl.dir/build
.PHONY : linefollowercldl/fast

#=============================================================================
# Target rules for targets named cldl_static_autogen_timestamp_deps

# Build rule for target.
cldl_static_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cldl_static_autogen_timestamp_deps
.PHONY : cldl_static_autogen_timestamp_deps

# fast build rule for target.
cldl_static_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/cldl/CMakeFiles/cldl_static_autogen_timestamp_deps.dir/build.make linefollower/cldl/CMakeFiles/cldl_static_autogen_timestamp_deps.dir/build
.PHONY : cldl_static_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named cldl_static_autogen

# Build rule for target.
cldl_static_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cldl_static_autogen
.PHONY : cldl_static_autogen

# fast build rule for target.
cldl_static_autogen/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/cldl/CMakeFiles/cldl_static_autogen.dir/build.make linefollower/cldl/CMakeFiles/cldl_static_autogen.dir/build
.PHONY : cldl_static_autogen/fast

#=============================================================================
# Target rules for targets named linefollowercldl_autogen_timestamp_deps

# Build rule for target.
linefollowercldl_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linefollowercldl_autogen_timestamp_deps
.PHONY : linefollowercldl_autogen_timestamp_deps

# fast build rule for target.
linefollowercldl_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/cldl/CMakeFiles/linefollowercldl_autogen_timestamp_deps.dir/build.make linefollower/cldl/CMakeFiles/linefollowercldl_autogen_timestamp_deps.dir/build
.PHONY : linefollowercldl_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named linefollowercldl_autogen

# Build rule for target.
linefollowercldl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linefollowercldl_autogen
.PHONY : linefollowercldl_autogen

# fast build rule for target.
linefollowercldl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f linefollower/cldl/CMakeFiles/linefollowercldl_autogen.dir/build.make linefollower/cldl/CMakeFiles/linefollowercldl_autogen.dir/build
.PHONY : linefollowercldl_autogen/fast

fcl.o: fcl.cpp.o
.PHONY : fcl.o

# target to build an object file
fcl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl.cpp.o
.PHONY : fcl.cpp.o

fcl.i: fcl.cpp.i
.PHONY : fcl.i

# target to preprocess a source file
fcl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl.cpp.i
.PHONY : fcl.cpp.i

fcl.s: fcl.cpp.s
.PHONY : fcl.s

# target to generate assembly for a file
fcl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl.cpp.s
.PHONY : fcl.cpp.s

fcl/bandpass.o: fcl/bandpass.cpp.o
.PHONY : fcl/bandpass.o

# target to build an object file
fcl/bandpass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/bandpass.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/bandpass.cpp.o
.PHONY : fcl/bandpass.cpp.o

fcl/bandpass.i: fcl/bandpass.cpp.i
.PHONY : fcl/bandpass.i

# target to preprocess a source file
fcl/bandpass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/bandpass.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/bandpass.cpp.i
.PHONY : fcl/bandpass.cpp.i

fcl/bandpass.s: fcl/bandpass.cpp.s
.PHONY : fcl/bandpass.s

# target to generate assembly for a file
fcl/bandpass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/bandpass.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/bandpass.cpp.s
.PHONY : fcl/bandpass.cpp.s

fcl/layer.o: fcl/layer.cpp.o
.PHONY : fcl/layer.o

# target to build an object file
fcl/layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/layer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/layer.cpp.o
.PHONY : fcl/layer.cpp.o

fcl/layer.i: fcl/layer.cpp.i
.PHONY : fcl/layer.i

# target to preprocess a source file
fcl/layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/layer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/layer.cpp.i
.PHONY : fcl/layer.cpp.i

fcl/layer.s: fcl/layer.cpp.s
.PHONY : fcl/layer.s

# target to generate assembly for a file
fcl/layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/layer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/layer.cpp.s
.PHONY : fcl/layer.cpp.s

fcl/neuron.o: fcl/neuron.cpp.o
.PHONY : fcl/neuron.o

# target to build an object file
fcl/neuron.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/neuron.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/neuron.cpp.o
.PHONY : fcl/neuron.cpp.o

fcl/neuron.i: fcl/neuron.cpp.i
.PHONY : fcl/neuron.i

# target to preprocess a source file
fcl/neuron.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/neuron.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/neuron.cpp.i
.PHONY : fcl/neuron.cpp.i

fcl/neuron.s: fcl/neuron.cpp.s
.PHONY : fcl/neuron.s

# target to generate assembly for a file
fcl/neuron.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl/neuron.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl/neuron.cpp.s
.PHONY : fcl/neuron.cpp.s

fcl_util.o: fcl_util.cpp.o
.PHONY : fcl_util.o

# target to build an object file
fcl_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl_util.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl_util.cpp.o
.PHONY : fcl_util.cpp.o

fcl_util.i: fcl_util.cpp.i
.PHONY : fcl_util.i

# target to preprocess a source file
fcl_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl_util.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl_util.cpp.i
.PHONY : fcl_util.cpp.i

fcl_util.s: fcl_util.cpp.s
.PHONY : fcl_util.s

# target to generate assembly for a file
fcl_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl.dir/build.make CMakeFiles/fcl.dir/fcl_util.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fcl_static.dir/build.make CMakeFiles/fcl_static.dir/fcl_util.cpp.s
.PHONY : fcl_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cldl_static_autogen"
	@echo "... cldl_static_autogen_timestamp_deps"
	@echo "... docs"
	@echo "... linefollower_autogen"
	@echo "... linefollower_autogen_timestamp_deps"
	@echo "... linefollowercldl_autogen"
	@echo "... linefollowercldl_autogen_timestamp_deps"
	@echo "... cldl_static"
	@echo "... fcl"
	@echo "... fcl_static"
	@echo "... linefollower"
	@echo "... linefollowercldl"
	@echo "... test_bandpass"
	@echo "... test_fcl"
	@echo "... test_fcl_filters"
	@echo "... test_layer"
	@echo "... test_neuron"
	@echo "... fcl.o"
	@echo "... fcl.i"
	@echo "... fcl.s"
	@echo "... fcl/bandpass.o"
	@echo "... fcl/bandpass.i"
	@echo "... fcl/bandpass.s"
	@echo "... fcl/layer.o"
	@echo "... fcl/layer.i"
	@echo "... fcl/layer.s"
	@echo "... fcl/neuron.o"
	@echo "... fcl/neuron.i"
	@echo "... fcl/neuron.s"
	@echo "... fcl_util.o"
	@echo "... fcl_util.i"
	@echo "... fcl_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

